/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_android_echoprint_lib_Codegen */

#ifndef _Included_org_android_echoprint_lib_Codegen
#define _Included_org_android_echoprint_lib_Codegen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_android_echoprint_lib_Codegen
 * Method:    codegen
 * Signature: ([FI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_android_echoprint_lib_Codegen_codegen
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
